{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "garage-admin-token" -}}
{{- $token := "" -}}
{{- if $existingSecret -}}
  {{- $token = index $existingSecret.data "token" | b64dec -}}
{{- else -}}
  {{- $token = randAlphaNum 32 -}}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: garage-admin-token
  labels:
    app: garage
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  token: "{{ $token }}"
