apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: {{ .Values.bucketName }}
spec:
  clusterRef:
    name: {{.Values.clusterRef}}
    namespace: {{ include "instanceNamespace" . }}
  bucketPermissions:
    - bucketRef: {{ .Values.bucketName }}
      read: true
      write: true
