apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.fullname" . }}-init
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
stringData:
  configure_gpg_environment.sh: |-
{{ .Files.Get "scripts/configure_gpg_environment.sh" | indent 4 }}
  init_directory_structure.sh: |-
{{ tpl (.Files.Get "scripts/init_directory_structure.sh.tpl") . | indent 4 }}
  configure_gitea.sh: |-
{{ tpl (.Files.Get "scripts/configure_gitea.sh.tpl") . | indent 4 }}
