{{- if .Values.backup.enabled -}}
apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mariadb.name" . }}
    helm.sh/chart: {{ include "mariadb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  mariaDbRef:
    name: {{ include "mariadb.fullname" . }}
  storage:
    schedule:
      {{/* Generate uniform random minute (0–59) */}}
      {{- $minute := (randNumeric 2 | atoi) -}}
      {{- if gt $minute 59 -}}{{- $minute = (mod $minute 60) -}}{{- end -}}

      {{/* Random index 0–7 */}}
      {{- $r := (mod (atoi (randNumeric 2)) 8) -}}

      {{/* Allowed night hours */}}
      {{- $nightHours := list 22 23 0 1 2 3 4 5 -}}

      {{- $hour := index $nightHours $r -}}
      cron: {{ printf "%d %d * * *" $minute $hour }}
    s3:
      bucket: {{ .Values.backup.s3.bucket }}
      endpoint: {{ .Values.backup.s3.endpoint }}
      accessKeyIdSecretKeyRef:
        name: backup
        key: access-key
      secretAccessKeySecretKeyRef:
        name: backup
        key: secret-key
      tls:
        enabled: true
  stagingStorage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: {{ .Values.storage.size }}
      accessModes:
        - ReadWriteOnce 
{{- end -}}
