{{- if .Values.backup.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: backup
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "mariadb.name" . }}
    helm.sh/chart: {{ include "mariadb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  access-key: {{ .Values.backup.s3.accessKey | b64enc | quote }}
  secret-key: {{ .Values.backup.s3.secretKey | b64enc | quote }}
{{- end -}}
