{{- if .Values.backup.enabled -}}
apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mariadb.name" . }}
    helm.sh/chart: {{ include "mariadb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  mariaDbRef:
    name: {{ include "mariadb.fullname" . }}
  maxRetention: {{ .Values.backup.maxRetention }}
  schedule:
    {{- $hourSeed := sha256sum (printf "%s-hour" .Release.Namespace) }}
    {{- $minuteSeed := sha256sum (printf "%s-minute" .Release.Namespace) }}
    {{/* Generate uniform random night hours (22-05) */}}
    {{- $hourInt := mod (adler32sum $hourSeed) 8 }}
    {{- $hour := mod (add 22 $hourInt) 24 }}
    {{/* Generate uniform random minute (0–59) */}}
    {{- $minute := mod (adler32sum $minuteSeed) 60 }}
    cron: {{ printf "%d %d * * *" $minute $hour }}
  storage:
    s3:
      bucket: {{ .Values.backup.s3.bucket }}
      endpoint: {{ .Values.backup.s3.endpoint }}
      {{- with .Values.backup.s3.prefix }}
      prefix: {{ . | toYaml | nindent 8 }}
      {{- end }}
      accessKeyIdSecretKeyRef:
        name: backup
        key: access-key
      secretAccessKeySecretKeyRef:
        name: backup
        key: secret-key
      tls:
        enabled: true
  stagingStorage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: {{ .Values.storage.size }}
      accessModes:
        - ReadWriteOnce 
{{- end -}}
