apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mariadb.name" . }}
    helm.sh/chart: {{ include "mariadb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  {{ if .Values.rootPasswordSecretKeyRef}}
  rootPasswordSecretKeyRef: {{ .Values.rootPasswordSecretKeyRef | toYaml | nindent 4 }}
  {{- else -}}
  rootPasswordSecretKeyRef:
    key: root-password
    name: {{ include "mariadb.fullname" . }}
  {{- end }}
  image: {{ .Values.image }}
  replicas: {{ .Values.replicas }}
  myCnf: {{- .Values.myCnf | toYaml | nindent 4 }}
  {{- with .Values.resources }}
  resources: {{ . | toYaml | nindent 4 }}
  {{- end }}
  metrics:
    enabled: {{ .Values.metrics.enabled }}
    exporter:
      image: {{ .Values.metrics.exporter.image }}
  galera:
    enabled: {{ .Values.galera.enabled }}
    config:
      reuseStorageVolume: {{ .Values.galera.config.reuseStorageVolume }}
    {{- with .Values.galera.providerOptions }}
    providerOptions: {{ . | toYaml | nindent 6 }}
    {{- end }}
  storage:
    size: {{ .Values.storage.size }}

