{{- if .Values.rootPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "mariadb.name" . }}
    helm.sh/chart: {{ include "mariadb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  root-password: {{ .Values.rootPassword | b64enc | quote }}
{{- end -}}
